In [12]:
import sys
import string
import os
import numpy as np
from math import pi
import scipy.stats
import warnings
import matplotlib as mpl
import matplotlib.pyplot as plt
from tqdm import tqdm

from bokeh.layouts import gridplot
from bokeh.plotting import output_file, figure, show
from bokeh.palettes import inferno
from bokeh.models import Label
from bokeh.models import Range1d
from bokeh.io import export_png
from bokeh.core.properties import value
from bokeh.models import ColumnDataSource
from bokeh.transform import dodge
%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
fig = plt.figure()
mpl.rcParams['figure.figsize'] = (8.0, 6.0)

<Figure size 432x288 with 0 Axes>

In [3]:
#Different lengths
mM = 50
lengths = ['500','1000','2000','4000','6000','8000','10000']
colors = inferno(len(lengths)+1)

p1 = figure(toolbar_location = None,
           x_axis_label='Radius of compression, nm', y_axis_label='Number of layers', 
           plot_width=800, plot_height=600,
           x_range = (4, 31), y_range = (0.8,8.2))
p1.xaxis.axis_label_text_font_size = "22pt"
p1.xaxis.major_label_text_font_size = "18pt"
p1.yaxis.axis_label_text_font_size = "22pt"
p1.yaxis.major_label_text_font_size = "18pt"
p2 = figure(toolbar_location = None,
           x_axis_label='Radius of compression, nm', y_axis_label='Interlayer distance, nm', 
           plot_width=800, plot_height=600,
           x_range = (4, 31), y_range = (1.2, 12.8))
p2.xaxis.axis_label_text_font_size = "22pt"
p2.xaxis.major_label_text_font_size = "18pt"
p2.yaxis.axis_label_text_font_size = "22pt"
p2.yaxis.major_label_text_font_size = "18pt"
# leg = "Mean squared error: %.2f\t" % err + 'Variance score: %.2f' % var_score
# mytext = Label(x=70, y=70, text=leg)
for bp,c in zip(lengths,colors):
    fname = f'../DNA/dsDNA/{bp}bp/{mM}mM/push_from_30nm/dsDNA_{bp}bp_{mM}mM_pressure_push.dat'
    with open(fname, 'r') as fh:
        max_frame = int(fh.readlines()[-1].split()[0]) // 10000
    rads = np.array([float(i.split('\t')[1].strip()) for i in open(fname)])[2:]
    fname = f'../DNA/dsDNA/{bp}bp/{mM}mM/push_from_30nm/layers.dat'
    lay_num =  np.array([float(i.split('\t')[1].strip()) for i in open(fname)])
    lay_dist = np.array([float(i.split('\t')[2].strip()) for i in open(fname)])
    
    inds = np.where(rads<=30)[0]
    print(f'Length = {bp}bp')
    p1.scatter(rads[inds], lay_num[inds], color = c, line_color=None, legend=bp, fill_alpha=0.5, size=5)
    p2.scatter(rads[inds], lay_dist[inds], line_color=None, color = c, legend=bp, fill_alpha=0.5, size=5)
    
p1.legend.label_text_font_size = "18pt"
p1.legend.location = "top_left"
p2.legend.label_text_font_size = "18pt"
p2.legend.location = "top_left"
# show(p1)
# show(p2)
# export_png(p1, filename=f'../DNA/dsDNA/plots/lay_num_lengths.png')
# export_png(p2, filename=f'../DNA/dsDNA/plots/lay_dist_lengths.png')

Length = 500bp
Length = 1000bp
Length = 2000bp
Length = 4000bp
Length = 6000bp
Length = 8000bp
Length = 10000bp


In [4]:
#For different concentrations
bp = 4000
mMs = ['0.1','2','5','12','50']
colors = inferno(len(mMs)+1)
p1 = figure(toolbar_location = None,
           x_axis_label='Radius of compression, nm', y_axis_label='Number of layers', 
           plot_width=800, plot_height=600,
           x_range = (9.6, 26.4), y_range = (0.8,8.2))
p1.xaxis.axis_label_text_font_size = "22pt"
p1.xaxis.major_label_text_font_size = "18pt"
p1.yaxis.axis_label_text_font_size = "22pt"
p1.yaxis.major_label_text_font_size = "18pt"
p2 = figure(toolbar_location = None,
           x_axis_label='Radius of compression, nm', y_axis_label='Interlayer distance, nm', 
           plot_width=800, plot_height=600,
           x_range = (9.6, 26.4), y_range = (1.2, 12.8))
p2.xaxis.axis_label_text_font_size = "22pt"
p2.xaxis.major_label_text_font_size = "18pt"
p2.yaxis.axis_label_text_font_size = "22pt"
p2.yaxis.major_label_text_font_size = "18pt"

for mM,c in zip(mMs,colors):
    fname = f'../DNA/dsDNA/{bp}bp/{mM}mM/push_from_30nm/dsDNA_{bp}bp_{mM}mM_pressure_push.dat'
    with open(fname, 'r') as fh:
        max_frame = int(fh.readlines()[-1].split()[0]) // 10000
    rads = np.array([float(i.split('\t')[1].strip()) for i in open(fname)])[2:]
    fname = f'../DNA/dsDNA/{bp}bp/{mM}mM/push_from_30nm/dist_last_layers.dat'
    lay_num =  np.array([float(i.split('\t')[1].strip()) for i in open(fname)])
    lay_dist = np.array([float(i.split('\t')[2].strip()) for i in open(fname)])
    
    inds = np.where(rads<=26)[0]

    p1.scatter(rads[inds], lay_num[inds], color = c, line_color=None, legend=mM, fill_alpha=0.6, size=5)
    p2.scatter(rads[inds], lay_dist[inds], line_color=None, color = c, legend=mM, fill_alpha=0.3, size=5)
    
p1.legend.label_text_font_size = "18pt"
p1.legend.location = "top_left"
p2.legend.label_text_font_size = "18pt"
p2.legend.location = "top_left"
# show(p)
# export_png(p1, filename=f'../DNA/dsDNA/plots/lay_num_mMs.png')
# export_png(p2, filename=f'../DNA/dsDNA/plots/lay_dist_mMs.png')

In [40]:
#Histogram for layers (pressure 100-300 atm)
mM = '50'
lengths = ['500','1000','2000','6000','8000','10000']
colors = inferno(len(lengths)+1)
to_plot = []

nums = np.arange(2,8).astype(str)
intervals = np.linspace(-0.3,0.3,len(lengths))

p = figure(x_range=nums, x_axis_label='Number of layers', y_axis_label=r'SMTH', 
        plot_width=800, plot_height=600)
p.xaxis.axis_label_text_font_size = "22pt"
p.xaxis.major_label_text_font_size = "18pt"
p.yaxis.axis_label_text_font_size = "22pt"
p.yaxis.major_label_text_font_size = "18pt"
p.toolbar.logo = None
p.toolbar_location = None


dl = intervals[-1]-intervals[-2]
for i,bp,c in zip(intervals,lengths,colors):
    
    fname = f'../DNA/dsDNA/{bp}bp/{mM}mM/push_from_30nm/dsDNA_{bp}bp_{mM}mM_pressure_push.dat'
    frames = np.array([int(i.split('\t')[0].strip()) for i in open(fname)]) // 10000
    pressure = np.array([float(i.split('\t')[2].strip())*1.6*9.87 for i in open(fname)])

    ind_start = np.where(pressure>=50)[0][0]
    ind_stop = np.where(pressure>=300)[0][0]

    f_lay = f'../DNA/dsDNA/{bp}bp/{mM}mM/push_from_30nm/layers.dat'
    num_lay = np.array([int(i.split('\t')[1].strip()) for i in open(f_lay)])
    to_plot.append(num_lay[(ind_start-1):(ind_stop-1)])
    hist, edges = np.histogram(num_lay[(ind_start-1):(ind_stop-1)], bins=np.arange(2,9), density=True)
    print(hist)
    data = {'nums' : nums,
            f'{bp}':hist
           }

    source = ColumnDataSource(data=data)
    p.vbar(x=dodge('nums', i, range=p.x_range), top=f'{bp}', width=dl, source=source,
       color=c, legend=value(f"{bp}"))


p.legend.label_text_font_size = "18pt"
show(p)
export_png(p, filename=f'../DNA/dsDNA/plots/num_lay_50-300atm.png')
# bins = np.arange(1.5, 9.5)
# plt.hist(to_plot, bins = bins, histtype='bar', label=lengths, normed=True)
# plt.legend()
# plt.savefig('../DNA/dsDNA/plots/num_lay_50-300atm.png', format='png', dpi=300)


[0.97315436 0.02348993 0.0033557  0.         0.         0.        ]
[0.2320442  0.74585635 0.02209945 0.         0.         0.        ]
[0.         0.82119205 0.17880795 0.         0.         0.        ]
[0.         0.         0.         0.82594937 0.17246835 0.00158228]
[0.         0.         0.         0.05873926 0.87249284 0.06876791]
[0.         0.         0.         0.02099738 0.82808399 0.15091864]


'/home/yagafarova/DNA/dsDNA/plots/num_lay_50-300atm.png'